name: Update Changelog

on:
  workflow_call:
    inputs:
      changelog:
        required: false
        default: CHANGELOG.md
        type: string
      branch:
        required: false
        default: main
        type: string

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update changelog
        uses: laravel/changelog-updater-action@v1
        with:
          filename: ${{ inputs.changelog }}

      - name: Commit changes
        run: |
          git config --global user.name "Laravel Bot"
          git config --global user.email "bot@laravel.com"
          git add ${{ inputs.changelog }}
          git diff --quiet && git diff --staged --quiet || git commit -m "Update changelog"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ inputs.branch }}
          github_token: ${{ github.token }}