name: Update Changelog

on:
  release:
    types: [released]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.target_commitish }}

      - name: Extract release date
        id: release_date
        run: |
          TIMESTAMP=$(git log -1 --date=unix --format=%ad '${{ github.event.release.tag_name }}')
          FORMATTED=$(date -u -d @$TIMESTAMP +%Y-%m-%d)
          echo "date=$FORMATTED" >> $GITHUB_OUTPUT

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          release-date: ${{ steps.release_date.outputs.date }}
          release-notes: ${{ github.event.release.body }}
          latest-version: ${{ github.event.release.tag_name }}
          compare-url-target-revision: ${{ github.event.release.target_commitish }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: ${{ github.event.release.target_commitish }}
          commit_message: "Update CHANGELOG.md"
          file_pattern: CHANGELOG.md
